config-version: 2

name: "leah_snowflake_jaffle_shop"
version: "3.0.0"
require-dbt-version: ">=1.5.0"

dbt-cloud:
  project-id: 275557

profile: default

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["data-tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

on-run-end:
  - "{{ dbt_artifacts.upload_results(results) }}"

vars:
  "dbt_date:time_zone": "America/Los_Angeles"

flags:
  enable_iceberg_materializations: true

models:
  leah_snowflake_jaffle_shop:
    staging:
      +materialized: view
    marts:
      +materialized: table
